USE [dbDOC_ph2]
GO

/****** Object:  Table [dbo].[TT_AA_BIHIN_SOFU_SHIJI_FAX]    Script Date: 2016/01/28 18:18:12 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[TT_AA_BIHIN_SOFU_SHIJI_FAX](
	[SHUPPINN_TOROKU_NO] [varchar](8) NOT NULL,
	[RENKEI_ZUMI_FLG] [char](1) NULL,
	[CREATE_DATE] [datetime] NULL,
	[CREATE_USER_CD] [varchar](10) NULL,
	[CREATE_PG_CD] [varchar](10) NULL,
	[UPDATE_DATE] [datetime] NULL,
	[UPDATE_USER_CD] [varchar](10) NULL,
	[UPDATE_PG_CD] [varchar](10) NULL,
	[DELETE_DATE] [datetime] NULL,
	[DELETE_FLG] [char](1) NULL,
 CONSTRAINT [PK_TT_AA_BIHIN_SOFU_SHIJI_FAX] PRIMARY KEY CLUSTERED 
(
	[SHUPPINN_TOROKU_NO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [dbDOC_DATA]
) ON [dbDOC_DATA]

GO

SET ANSI_PADDING OFF
GO

