USE [dbDOC_ph2]
GO

/****** Object:  Table [dbo].[TT_DOC_HENSO_IF]    Script Date: 2016/01/28 18:24:56 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[TT_DOC_HENSO_IF](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[HENSO_IRAI_DATE] [datetime] NULL,
	[SHOP_CD] [char](6) NULL,
	[TANTOSHA_NAME] [varchar](40) NULL,
	[GENSHA_LOCATION] [varchar](25) NULL,
	[CAR_NAME] [varchar](100) NULL,
	[CHASSIS_NO] [varchar](25) NULL,
	[SHIIRE_SAKI] [varchar](20) NULL,
	[SHUPPINN_TOROKU_NO] [varchar](8) NOT NULL,
	[DOC_HENSO_RIYU] [varchar](1000) NULL,
	[NOTE] [varchar](1000) NULL,
	[JISHAMEI_DOC_MAKE_YOUHI] [varchar](1000) NULL,
	[HENSO_ZUMI_FLG] [char](1) NULL,
	[CREATE_DATE] [datetime] NULL,
	[CREATE_USER_CD] [varchar](10) NULL,
	[CREATE_PG_CD] [varchar](10) NULL,
	[UPDATE_DATE] [datetime] NULL,
	[UPDATE_USER_CD] [varchar](10) NULL,
	[UPDATE_PG_CD] [varchar](10) NULL,
	[DELETE_DATE] [datetime] NULL,
	[DELETE_FLG] [char](1) NULL,
 CONSTRAINT [PK_TT_DOC_HENSO_IF] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [dbDOC_DATA]
) ON [dbDOC_DATA]

GO

SET ANSI_PADDING OFF
GO

