USE [dbDOC_ph2]
GO

/****** Object:  Table [dbo].[TT_GHQ_DOC_UKETORI_OUTPUT]    Script Date: 2016/01/28 18:15:04 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[TT_GHQ_DOC_UKETORI_OUTPUT](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[CHASSIS_NO] [varchar](25) NULL,
	[SHOP_CD] [char](6) NULL,
	[SHUPPINN_TOROKU_NO] [varchar](8) NULL,
	[CAR_TYPE] [char](2) NULL,
	[UKETORIJI_SHORUI_TYPE] [char](2) NULL,
	[LICENSE_PLATE] [varchar](30) NULL,
	[SHORUI_FINISH_DATE] [char](8) NULL,
	[SHORUI_LIMIT_DATE] [char](8) NULL,
	[Incompleteness] [char](1) NULL,
	[JISHAMEI_FLG] [char](1) NULL,
	[DOC_CONTROL_NO] [varchar](13) NOT NULL,
	[RENKEI_ZUMI_FLG] [char](1) NULL,
	[NOTE] [varchar](200) NULL,
	[CREATE_DATE] [datetime] NULL,
	[CREATE_USER_CD] [varchar](10) NULL,
	[CREATE_PG_CD] [varchar](10) NULL,
	[UPDATE_DATE] [datetime] NULL,
	[UPDATE_USER_CD] [varchar](10) NULL,
	[UPDATE_PG_CD] [varchar](10) NULL,
	[DELETE_DATE] [datetime] NULL,
	[DELETE_FLG] [char](1) NULL,
 CONSTRAINT [PK_TT_GHQ_DOC_UKETORI_OUTPUT] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [dbDOC_DATA]
) ON [dbDOC_DATA]

GO

SET ANSI_PADDING OFF
GO

