USE [dbDOC_ph2]
GO

/****** Object:  Table [dbo].[TT_GHQ_DOC_MEIHEN_OUTPUT]    Script Date: 2016/01/28 18:14:53 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[TT_GHQ_DOC_MEIHEN_OUTPUT](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[KEI_CAR_FLG] [char](1) NULL,
	[TOROKU_NO] [varchar](30) NULL,
	[TOROKU_YEAR] [varchar](2) NULL,
	[TOROKU_MONTH] [varchar](2) NULL,
	[TOROKU_DAY] [varchar](2) NULL,
	[CHASSIS_NO] [varchar](25) NULL,
	[JOSHA_TEIIN_NUM] [int] NULL,
	[CC] [real] NULL,
	[NOTE] [varchar](200) NULL,
	[RENKEI_ZUMI_FLG] [char](1) NULL,
	[CREATE_DATE] [datetime] NULL,
	[CREATE_USER_CD] [varchar](10) NULL,
	[CREATE_PG_CD] [varchar](10) NULL,
	[UPDATE_DATE] [datetime] NULL,
	[UPDATE_USER_CD] [varchar](10) NULL,
	[UPDATE_PG_CD] [varchar](10) NULL,
	[DELETE_DATE] [datetime] NULL,
	[DELETE_FLG] [char](1) NULL,
 CONSTRAINT [PK_TT_GHQ_DOC_MEIHEN_OUTPUT] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [dbDOC_DATA]
) ON [dbDOC_DATA]

GO

SET ANSI_PADDING OFF
GO

